# Generated by Django 4.2.3 on 2023-07-31 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='employee',
            new_name='member',
        ),
    ]
