# Generated by Django 4.2.3 on 2023-07-31 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_project_assigned_to_alter_project_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
    ]
