# Generated by Django 4.2.3 on 2023-07-31 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project_app', '0004_remove_project_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_app', to=settings.AUTH_USER_MODEL),
        ),
    ]
