# Generated by Django 4.2.3 on 2023-08-01 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0006_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='employee',
            new_name='member',
        ),
    ]
